In [2]:
import tensorflow as tf

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])
dataset = dataset.map(lambda x: x * 2).batch(2)
for batch in dataset:
    print(batch)

tf.Tensor([2 4], shape=(2,), dtype=int32)
tf.Tensor([6 8], shape=(2,), dtype=int32)
tf.Tensor([10], shape=(1,), dtype=int32)
