In [49]:
import numpy as np
import gymnasium as gym

Exercice 1 : Exploration de l'Environnement FrozenLake

In [50]:
# Charger l’environnement FrozenLake
env = gym.make("FrozenLake-v1", is_slippery=True, render_mode="ansi")
print("Espace d'états:", env.observation_space)
print("Espace d'actions:", env.action_space)

Espace d'états: Discrete(16)
Espace d'actions: Discrete(4)


In [51]:
# Exécution d'une boucle d'interaction aléatoire
num_episodes = 5
for episode in range(num_episodes):
    state = env.reset()[0]
    done = False
    while not done:
        action = env.action_space.sample()  # Choix aléatoire d'une action
        next_state, reward, done, _, _ = env.step(action)
        print(f"Épisode {episode+1}, État: {state}, Action: {action}, Récompense: {reward}")
        state = next_state

Épisode 1, État: 0, Action: 0, Récompense: 0.0
Épisode 1, État: 0, Action: 2, Récompense: 0.0
Épisode 1, État: 4, Action: 2, Récompense: 0.0
Épisode 1, État: 0, Action: 1, Récompense: 0.0
Épisode 1, État: 1, Action: 0, Récompense: 0.0
Épisode 1, État: 0, Action: 3, Récompense: 0.0
Épisode 1, État: 0, Action: 3, Récompense: 0.0
Épisode 1, État: 0, Action: 2, Récompense: 0.0
Épisode 1, État: 0, Action: 0, Récompense: 0.0
Épisode 1, État: 4, Action: 3, Récompense: 0.0
Épisode 2, État: 0, Action: 1, Récompense: 0.0
Épisode 2, État: 0, Action: 0, Récompense: 0.0
Épisode 2, État: 0, Action: 3, Récompense: 0.0
Épisode 2, État: 0, Action: 0, Récompense: 0.0
Épisode 2, État: 0, Action: 3, Récompense: 0.0
Épisode 2, État: 1, Action: 2, Récompense: 0.0
Épisode 2, État: 1, Action: 3, Récompense: 0.0
Épisode 2, État: 2, Action: 1, Récompense: 0.0
Épisode 2, État: 6, Action: 1, Récompense: 0.0
Épisode 3, État: 0, Action: 2, Récompense: 0.0
Épisode 3, État: 0, Action: 3, Récompense: 0.0
Épisode 3, Ét

Exercice 2 : Implémentation de la Q-Table

In [52]:
num_states = env.observation_space.n
num_actions = env.action_space.n
q_table = np.zeros((num_states, num_actions))
print("\nQ-Table initiale :\n", q_table)


Q-Table initiale :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Exercice 3 : Implémentation du Q-Learning

In [53]:
alpha = 0.1 
gamma = 0.99  # Facteur de discount
epsilon = 1.0  # Probabilité d'exploration
epsilon_decay = 0.99  # Réduction progressive d'epsilon
epsilon_min = 0.01  # Valeur minimale d'epsilon
num_episodes = 5000  # Nombre d'épisodes

In [54]:
for episode in range(num_episodes):
    state = env.reset()[0]
    done = False
    while not done:
        if np.random.rand() < epsilon:
            action = env.action_space.sample() 
        else:
            action = np.argmax(q_table[state]) 
        next_state, reward, done, _, _ = env.step(action)
        q_table[state, action] = q_table[state, action] + alpha * (reward + gamma * np.max(q_table[next_state]) - q_table[state, action])
        state = next_state
    epsilon = max(epsilon_min, epsilon * epsilon_decay)
print("\nQ-Table après apprentissage :\n", q_table)


Q-Table après apprentissage :
 [[4.51261598e-01 3.27202716e-01 4.24400238e-01 3.83616041e-01]
 [8.39270957e-02 2.06148740e-01 2.00289590e-02 4.12888761e-05]
 [2.16609470e-01 4.54506467e-02 2.81647712e-02 8.05281596e-02]
 [1.51059811e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.68230800e-01 2.51245700e-01 3.07670628e-01 2.99511504e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.35648906e-01 4.44087281e-02 4.60382300e-02 3.89128110e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.48854972e-01 3.17050232e-01 3.91892715e-01 5.08697830e-01]
 [4.89743938e-01 5.70186903e-01 4.37221809e-01 4.42919484e-01]
 [6.17890870e-01 2.40981700e-01 2.77602649e-01 1.45347395e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.37557365e-01 5.37641232e-01 6.49707659e-01 4.04055989e-01]
 [4.21085679e-01 8.54130347e-01 7.11376918e-01 6.25707656e-01]
 [0.00000000e+00 0.0000

Exercice 4 : Évaluation des Performances

In [ ]:
num_test_episodes = 100
successes = 0

for _ in range(num_test_episodes):
    state = env.reset()[0]
    done = False
    while not done:
        action = np.argmax(q_table[state])  
        state, reward, done, _, _ = env.step(action)
        if reward == 1:
            successes += 1
print(f"\nTaux de réussite après apprentissage : {successes}/{num_test_episodes} ({(successes/num_test_episodes)*100:.2f}%)")


Taux de réussite après apprentissage : 76/100 (76.00%)
